# Generated by Django 4.1.2 on 2022-11-28 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='website',
        ),
    ]
