# Generated by Django 4.1.2 on 2022-11-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_remove_contact_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('about', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Bmi',
        ),
    ]
