# Generated by Django 4.1.2 on 2022-12-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("novel", "0003_bod_delete_bmi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teachers",
            name="fb_account",
        ),
        migrations.RemoveField(
            model_name="teachers",
            name="google_plus_account",
        ),
        migrations.RemoveField(
            model_name="teachers",
            name="insta_account",
        ),
        migrations.RemoveField(
            model_name="teachers",
            name="twitter_account",
        ),
    ]
